# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

import sys
import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import * # QApplication, QWidget, QPushButton, QMessageBox, QLineEdit, QInputDialog


class Coin(object):
    def __init__(self):
        self.coin = {1000: 0, 500: 0, 100: 0, 50: 0, 10: 0}

    def IncreaseCoin(self, type, amount):
        self.coin[type] += amount

    def DecreaseCoin(self, type, amount):
        self.coin[type] -= amount

    def GetSum(self):
        return (self.coin[1000] * 1000) + (self.coin[500] * 500) + (self.coin[100] * 100) + (self.coin[50] * 50) + (self.coin[10] * 10)

    def GetCoin(self, type):
        return self.coin[type]

    def GetCoinIndex(self, index):
        return list(self.coin.keys())[index], list(self.coin.values())[index]

    def Reset(self):
        self.coin[1000] = 0
        self.coin[500] = 0
        self.coin[100] = 0
        self.coin[50] = 0
        self.coin[10] = 0

class UiDialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 600)

        self.btnDeveloper = QtWidgets.QPushButton(Dialog)
        self.btnDeveloper.setEnabled(True)
        self.btnDeveloper.setGeometry(QtCore.QRect(20, 550, 275, 30))
        self.btnDeveloper.setAutoDefault(False)
        self.btnDeveloper.setObjectName("btnDeveloper")
        self.imgIcis1 = QtWidgets.QLabel(Dialog)
        self.imgIcis1.setEnabled(True)
        self.imgIcis1.setGeometry(QtCore.QRect(-5, 20, 100, 100))
        self.imgIcis1.setText("")
        self.imgIcis1.setPixmap(QtGui.QPixmap("img/icis.png"))
        self.imgIcis1.setScaledContents(True)
        self.imgIcis1.setObjectName("imgIcis1")
        self.imgLemon1 = QtWidgets.QLabel(Dialog)
        self.imgLemon1.setEnabled(True)
        self.imgLemon1.setGeometry(QtCore.QRect(145, 20, 100, 100))
        self.imgLemon1.setText("")
        self.imgLemon1.setPixmap(QtGui.QPixmap("img/lemon.png"))
        self.imgLemon1.setScaledContents(True)
        self.imgLemon1.setObjectName("imgLemon1")
        self.imgIcis2 = QtWidgets.QLabel(Dialog)
        self.imgIcis2.setEnabled(True)
        self.imgIcis2.setGeometry(QtCore.QRect(45, 20, 100, 100))
        self.imgIcis2.setText("")
        self.imgIcis2.setPixmap(QtGui.QPixmap("img/icis.png"))
        self.imgIcis2.setScaledContents(True)
        self.imgIcis2.setObjectName("imgIcis2")
        self.imgIcis3 = QtWidgets.QLabel(Dialog)
        self.imgIcis3.setEnabled(True)
        self.imgIcis3.setGeometry(QtCore.QRect(95, 20, 100, 100))
        self.imgIcis3.setText("")
        self.imgIcis3.setPixmap(QtGui.QPixmap("img/icis.png"))
        self.imgIcis3.setScaledContents(True)
        self.imgIcis3.setObjectName("imgIcis3")
        self.imgLemon2 = QtWidgets.QLabel(Dialog)
        self.imgLemon2.setEnabled(True)
        self.imgLemon2.setGeometry(QtCore.QRect(195, 20, 100, 100))
        self.imgLemon2.setText("")
        self.imgLemon2.setPixmap(QtGui.QPixmap("img/lemon.png"))
        self.imgLemon2.setScaledContents(True)
        self.imgLemon2.setObjectName("imgLemon2")
        self.imgCorn1 = QtWidgets.QLabel(Dialog)
        self.imgCorn1.setEnabled(True)
        self.imgCorn1.setGeometry(QtCore.QRect(245, 20, 100, 100))
        self.imgCorn1.setText("")
        self.imgCorn1.setPixmap(QtGui.QPixmap("img/corn.png"))
        self.imgCorn1.setScaledContents(True)
        self.imgCorn1.setObjectName("imgCorn1")
        self.imgCorn2 = QtWidgets.QLabel(Dialog)
        self.imgCorn2.setEnabled(True)
        self.imgCorn2.setGeometry(QtCore.QRect(295, 20, 100, 100))
        self.imgCorn2.setText("")
        self.imgCorn2.setPixmap(QtGui.QPixmap("img/corn.png"))
        self.imgCorn2.setScaledContents(True)
        self.imgCorn2.setObjectName("imgCorn2")
        self.imgBurdock = QtWidgets.QLabel(Dialog)
        self.imgBurdock.setEnabled(True)
        self.imgBurdock.setGeometry(QtCore.QRect(345, 20, 100, 100))
        self.imgBurdock.setText("")
        self.imgBurdock.setPixmap(QtGui.QPixmap("img/burdock.png"))
        self.imgBurdock.setScaledContents(True)
        self.imgBurdock.setObjectName("imgBurdock")
        self.imgTrevi1 = QtWidgets.QLabel(Dialog)
        self.imgTrevi1.setEnabled(True)
        self.imgTrevi1.setGeometry(QtCore.QRect(395, 20, 100, 100))
        self.imgTrevi1.setText("")
        self.imgTrevi1.setPixmap(QtGui.QPixmap("img/trevi.png"))
        self.imgTrevi1.setScaledContents(True)
        self.imgTrevi1.setObjectName("imgTrevi1")
        self.imgTrevi2 = QtWidgets.QLabel(Dialog)
        self.imgTrevi2.setEnabled(True)
        self.imgTrevi2.setGeometry(QtCore.QRect(445, 20, 100, 100))
        self.imgTrevi2.setText("")
        self.imgTrevi2.setPixmap(QtGui.QPixmap("img/trevi.png"))
        self.imgTrevi2.setScaledContents(True)
        self.imgTrevi2.setObjectName("imgTrevi2")
        self.btnOrderIcis2 = QtWidgets.QPushButton(Dialog)
        self.btnOrderIcis2.setGeometry(QtCore.QRect(70, 150, 50, 30))
        self.btnOrderIcis2.setAutoDefault(False)
        self.btnOrderIcis2.setObjectName("btnOrderIcis2")
        self.priceIcis1 = QtWidgets.QLabel(Dialog)
        self.priceIcis1.setGeometry(QtCore.QRect(22, 130, 50, 16))
        self.priceIcis1.setAlignment(QtCore.Qt.AlignCenter)
        self.priceIcis1.setObjectName("priceIcis1")
        self.priceIcis2 = QtWidgets.QLabel(Dialog)
        self.priceIcis2.setGeometry(QtCore.QRect(72, 130, 50, 16))
        self.priceIcis2.setAlignment(QtCore.Qt.AlignCenter)
        self.priceIcis2.setObjectName("priceIcis2")
        self.priceLemon1 = QtWidgets.QLabel(Dialog)
        self.priceLemon1.setGeometry(QtCore.QRect(172, 130, 50, 16))
        self.priceLemon1.setAlignment(QtCore.Qt.AlignCenter)
        self.priceLemon1.setObjectName("priceLemon1")
        self.btnOrderIcis3 = QtWidgets.QPushButton(Dialog)
        self.btnOrderIcis3.setGeometry(QtCore.QRect(120, 150, 50, 30))
        self.btnOrderIcis3.setAutoDefault(False)
        self.btnOrderIcis3.setObjectName("btnOrderIcis3")
        self.priceIcis3 = QtWidgets.QLabel(Dialog)
        self.priceIcis3.setGeometry(QtCore.QRect(122, 130, 50, 16))
        self.priceIcis3.setAlignment(QtCore.Qt.AlignCenter)
        self.priceIcis3.setObjectName("priceIcis3")
        self.btnOrderLemon1 = QtWidgets.QPushButton(Dialog)
        self.btnOrderLemon1.setGeometry(QtCore.QRect(170, 150, 50, 30))
        self.btnOrderLemon1.setAutoDefault(False)
        self.btnOrderLemon1.setObjectName("btnOrderLemon1")
        self.priceCorn1 = QtWidgets.QLabel(Dialog)
        self.priceCorn1.setGeometry(QtCore.QRect(272, 130, 50, 16))
        self.priceCorn1.setAlignment(QtCore.Qt.AlignCenter)
        self.priceCorn1.setObjectName("priceCorn1")
        self.priceCorn2 = QtWidgets.QLabel(Dialog)
        self.priceCorn2.setGeometry(QtCore.QRect(322, 130, 50, 16))
        self.priceCorn2.setAlignment(QtCore.Qt.AlignCenter)
        self.priceCorn2.setObjectName("priceCorn2")
        self.priceBurdock = QtWidgets.QLabel(Dialog)
        self.priceBurdock.setGeometry(QtCore.QRect(372, 130, 50, 16))
        self.priceBurdock.setAlignment(QtCore.Qt.AlignCenter)
        self.priceBurdock.setObjectName("priceBurdock")
        self.btnOrderLemon2 = QtWidgets.QPushButton(Dialog)
        self.btnOrderLemon2.setGeometry(QtCore.QRect(220, 150, 50, 30))
        self.btnOrderLemon2.setAutoDefault(False)
        self.btnOrderLemon2.setObjectName("btnOrderLemon2")
        self.priceLemon2 = QtWidgets.QLabel(Dialog)
        self.priceLemon2.setGeometry(QtCore.QRect(222, 130, 50, 16))
        self.priceLemon2.setAlignment(QtCore.Qt.AlignCenter)
        self.priceLemon2.setObjectName("priceLemon2")
        self.btnOrderCorn2 = QtWidgets.QPushButton(Dialog)
        self.btnOrderCorn2.setGeometry(QtCore.QRect(320, 150, 50, 30))
        self.btnOrderCorn2.setAutoDefault(False)
        self.btnOrderCorn2.setObjectName("btnOrderCorn2")
        self.btnOrderBurdock = QtWidgets.QPushButton(Dialog)
        self.btnOrderBurdock.setGeometry(QtCore.QRect(370, 150, 50, 30))
        self.btnOrderBurdock.setAutoDefault(False)
        self.btnOrderBurdock.setObjectName("btnOrderBurdock")
        self.btnOrderCorn = QtWidgets.QPushButton(Dialog)
        self.btnOrderCorn.setGeometry(QtCore.QRect(270, 150, 50, 30))
        self.btnOrderCorn.setAutoDefault(False)
        self.btnOrderCorn.setObjectName("btnOrderCorn")
        self.priceTrevi2 = QtWidgets.QLabel(Dialog)
        self.priceTrevi2.setGeometry(QtCore.QRect(472, 130, 50, 16))
        self.priceTrevi2.setAlignment(QtCore.Qt.AlignCenter)
        self.priceTrevi2.setObjectName("priceTrevi2")
        self.priceTrevi1 = QtWidgets.QLabel(Dialog)
        self.priceTrevi1.setGeometry(QtCore.QRect(422, 130, 50, 16))
        self.priceTrevi1.setAlignment(QtCore.Qt.AlignCenter)
        self.priceTrevi1.setObjectName("priceTrevi1")
        self.btnOrderTrevi2 = QtWidgets.QPushButton(Dialog)
        self.btnOrderTrevi2.setGeometry(QtCore.QRect(470, 150, 50, 30))
        self.btnOrderTrevi2.setAutoDefault(False)
        self.btnOrderTrevi2.setObjectName("btnOrderTrevi2")
        self.btnOrderTrevi1 = QtWidgets.QPushButton(Dialog)
        self.btnOrderTrevi1.setGeometry(QtCore.QRect(420, 150, 50, 30))
        self.btnOrderTrevi1.setAutoDefault(False)
        self.btnOrderTrevi1.setObjectName("btnOrderTrevi1")
        self.btnOrderIcis1 = QtWidgets.QPushButton(Dialog)
        self.btnOrderIcis1.setGeometry(QtCore.QRect(20, 150, 50, 30))
        self.btnOrderIcis1.setAutoDefault(False)
        self.btnOrderIcis1.setObjectName("btnOrderIcis1")
        self.btnOrderSparklingGrape = QtWidgets.QPushButton(Dialog)
        self.btnOrderSparklingGrape.setGeometry(QtCore.QRect(470, 330, 50, 30))
        self.btnOrderSparklingGrape.setAutoDefault(False)
        self.btnOrderSparklingGrape.setObjectName("btnOrderSparklingGrape")
        self.imgCocorich1 = QtWidgets.QLabel(Dialog)
        self.imgCocorich1.setEnabled(True)
        self.imgCocorich1.setGeometry(QtCore.QRect(193, 200, 100, 100))
        self.imgCocorich1.setText("")
        self.imgCocorich1.setPixmap(QtGui.QPixmap("img/cocoRich.png"))
        self.imgCocorich1.setScaledContents(True)
        self.imgCocorich1.setObjectName("imgCocorich1")
        self.imgCocorich2 = QtWidgets.QLabel(Dialog)
        self.imgCocorich2.setEnabled(True)
        self.imgCocorich2.setGeometry(QtCore.QRect(243, 200, 100, 100))
        self.imgCocorich2.setText("")
        self.imgCocorich2.setPixmap(QtGui.QPixmap("img/cocoRich.png"))
        self.imgCocorich2.setScaledContents(True)
        self.imgCocorich2.setObjectName("imgCocorich2")
        self.imgSparklingApple2 = QtWidgets.QLabel(Dialog)
        self.imgSparklingApple2.setEnabled(True)
        self.imgSparklingApple2.setGeometry(QtCore.QRect(393, 200, 100, 100))
        self.imgSparklingApple2.setText("")
        self.imgSparklingApple2.setPixmap(QtGui.QPixmap("img/sparklingApple.png"))
        self.imgSparklingApple2.setScaledContents(True)
        self.imgSparklingApple2.setObjectName("imgSparklingApple2")
        self.btnOrderCocoRich1 = QtWidgets.QPushButton(Dialog)
        self.btnOrderCocoRich1.setGeometry(QtCore.QRect(220, 330, 50, 30))
        self.btnOrderCocoRich1.setAutoDefault(False)
        self.btnOrderCocoRich1.setObjectName("btnOrderCocoRich1")
        self.imgCider = QtWidgets.QLabel(Dialog)
        self.imgCider.setEnabled(True)
        self.imgCider.setGeometry(QtCore.QRect(143, 200, 100, 100))
        self.imgCider.setText("")
        self.imgCider.setPixmap(QtGui.QPixmap("img/cider.png"))
        self.imgCider.setScaledContents(True)
        self.imgCider.setObjectName("imgCider")
        self.btnOrderSparklingApple1 = QtWidgets.QPushButton(Dialog)
        self.btnOrderSparklingApple1.setGeometry(QtCore.QRect(370, 330, 50, 30))
        self.btnOrderSparklingApple1.setAutoDefault(False)
        self.btnOrderSparklingApple1.setObjectName("btnOrderSparklingApple1")
        self.imgMilkis = QtWidgets.QLabel(Dialog)
        self.imgMilkis.setEnabled(True)
        self.imgMilkis.setGeometry(QtCore.QRect(-7, 200, 100, 100))
        self.imgMilkis.setText("")
        self.imgMilkis.setPixmap(QtGui.QPixmap("img/milkis.png"))
        self.imgMilkis.setScaledContents(True)
        self.imgMilkis.setObjectName("imgMilkis")
        self.priceSparklingApple2 = QtWidgets.QLabel(Dialog)
        self.priceSparklingApple2.setGeometry(QtCore.QRect(420, 310, 50, 16))
        self.priceSparklingApple2.setAlignment(QtCore.Qt.AlignCenter)
        self.priceSparklingApple2.setObjectName("priceSparklingApple2")
        self.priceMilkis = QtWidgets.QLabel(Dialog)
        self.priceMilkis.setGeometry(QtCore.QRect(20, 310, 50, 16))
        self.priceMilkis.setAlignment(QtCore.Qt.AlignCenter)
        self.priceMilkis.setObjectName("priceMilkis")
        self.imgHotsix = QtWidgets.QLabel(Dialog)
        self.imgHotsix.setEnabled(True)
        self.imgHotsix.setGeometry(QtCore.QRect(93, 200, 100, 100))
        self.imgHotsix.setText("")
        self.imgHotsix.setPixmap(QtGui.QPixmap("img/hotsix.png"))
        self.imgHotsix.setScaledContents(True)
        self.imgHotsix.setObjectName("imgHotsix")
        self.priceCocoRich1 = QtWidgets.QLabel(Dialog)
        self.priceCocoRich1.setGeometry(QtCore.QRect(220, 310, 50, 16))
        self.priceCocoRich1.setAlignment(QtCore.Qt.AlignCenter)
        self.priceCocoRich1.setObjectName("priceCocoRich1")
        self.btnOrderHotsix = QtWidgets.QPushButton(Dialog)
        self.btnOrderHotsix.setGeometry(QtCore.QRect(120, 330, 50, 30))
        self.btnOrderHotsix.setAutoDefault(False)
        self.btnOrderHotsix.setObjectName("btnOrderHotsix")
        self.btnOrderMilkis = QtWidgets.QPushButton(Dialog)
        self.btnOrderMilkis.setGeometry(QtCore.QRect(20, 330, 50, 30))
        self.btnOrderMilkis.setAutoDefault(False)
        self.btnOrderMilkis.setObjectName("btnOrderMilkis")
        self.btnOrderPepsi = QtWidgets.QPushButton(Dialog)
        self.btnOrderPepsi.setGeometry(QtCore.QRect(70, 330, 50, 30))
        self.btnOrderPepsi.setAutoDefault(False)
        self.btnOrderPepsi.setObjectName("btnOrderPepsi")
        self.priceCider = QtWidgets.QLabel(Dialog)
        self.priceCider.setGeometry(QtCore.QRect(170, 310, 50, 16))
        self.priceCider.setAlignment(QtCore.Qt.AlignCenter)
        self.priceCider.setObjectName("priceCider")
        self.btnOrderCocoRich2 = QtWidgets.QPushButton(Dialog)
        self.btnOrderCocoRich2.setGeometry(QtCore.QRect(270, 330, 50, 30))
        self.btnOrderCocoRich2.setAutoDefault(False)
        self.btnOrderCocoRich2.setObjectName("btnOrderCocoRich2")
        self.imgSparklingApple1 = QtWidgets.QLabel(Dialog)
        self.imgSparklingApple1.setEnabled(True)
        self.imgSparklingApple1.setGeometry(QtCore.QRect(343, 200, 100, 100))
        self.imgSparklingApple1.setText("")
        self.imgSparklingApple1.setPixmap(QtGui.QPixmap("img/sparklingApple.png"))
        self.imgSparklingApple1.setScaledContents(True)
        self.imgSparklingApple1.setObjectName("imgSparklingApple1")
        self.imgPepsi = QtWidgets.QLabel(Dialog)
        self.imgPepsi.setEnabled(True)
        self.imgPepsi.setGeometry(QtCore.QRect(43, 200, 100, 100))
        self.imgPepsi.setText("")
        self.imgPepsi.setPixmap(QtGui.QPixmap("img/pepsi.png"))
        self.imgPepsi.setScaledContents(True)
        self.imgPepsi.setObjectName("imgPepsi")
        self.imgLipton = QtWidgets.QLabel(Dialog)
        self.imgLipton.setEnabled(True)
        self.imgLipton.setGeometry(QtCore.QRect(293, 200, 100, 100))
        self.imgLipton.setText("")
        self.imgLipton.setPixmap(QtGui.QPixmap("img/lipton.png"))
        self.imgLipton.setScaledContents(True)
        self.imgLipton.setObjectName("imgLipton")
        self.priceLipton = QtWidgets.QLabel(Dialog)
        self.priceLipton.setGeometry(QtCore.QRect(320, 310, 50, 16))
        self.priceLipton.setAlignment(QtCore.Qt.AlignCenter)
        self.priceLipton.setObjectName("priceLipton")
        self.btnOrderSparklingApple2 = QtWidgets.QPushButton(Dialog)
        self.btnOrderSparklingApple2.setGeometry(QtCore.QRect(420, 330, 50, 30))
        self.btnOrderSparklingApple2.setAutoDefault(False)
        self.btnOrderSparklingApple2.setObjectName("btnOrderSparklingApple2")
        self.btnOrderCider = QtWidgets.QPushButton(Dialog)
        self.btnOrderCider.setGeometry(QtCore.QRect(170, 330, 50, 30))
        self.btnOrderCider.setAutoDefault(False)
        self.btnOrderCider.setObjectName("btnOrderCider")
        self.imgSparklingGrape = QtWidgets.QLabel(Dialog)
        self.imgSparklingGrape.setEnabled(True)
        self.imgSparklingGrape.setGeometry(QtCore.QRect(443, 200, 100, 100))
        self.imgSparklingGrape.setText("")
        self.imgSparklingGrape.setPixmap(QtGui.QPixmap("img/sparkingGrape.png"))
        self.imgSparklingGrape.setScaledContents(True)
        self.imgSparklingGrape.setObjectName("imgSparklingGrape")
        self.priceHotsix = QtWidgets.QLabel(Dialog)
        self.priceHotsix.setGeometry(QtCore.QRect(120, 310, 50, 16))
        self.priceHotsix.setAlignment(QtCore.Qt.AlignCenter)
        self.priceHotsix.setObjectName("priceHotsix")
        self.pricePepsi = QtWidgets.QLabel(Dialog)
        self.pricePepsi.setGeometry(QtCore.QRect(70, 310, 50, 16))
        self.pricePepsi.setAlignment(QtCore.Qt.AlignCenter)
        self.pricePepsi.setObjectName("pricePepsi")
        self.priceCocoRich2 = QtWidgets.QLabel(Dialog)
        self.priceCocoRich2.setGeometry(QtCore.QRect(270, 310, 50, 16))
        self.priceCocoRich2.setAlignment(QtCore.Qt.AlignCenter)
        self.priceCocoRich2.setObjectName("priceCocoRich2")
        self.priceOrderSparklingApple = QtWidgets.QLabel(Dialog)
        self.priceOrderSparklingApple.setGeometry(QtCore.QRect(470, 310, 50, 16))
        self.priceOrderSparklingApple.setAlignment(QtCore.Qt.AlignCenter)
        self.priceOrderSparklingApple.setObjectName("priceOrderSparklingApple")
        self.priceSparklingApple1 = QtWidgets.QLabel(Dialog)
        self.priceSparklingApple1.setGeometry(QtCore.QRect(370, 310, 50, 16))
        self.priceSparklingApple1.setAlignment(QtCore.Qt.AlignCenter)
        self.priceSparklingApple1.setObjectName("priceSparklingApple1")
        self.btnOrderLipton = QtWidgets.QPushButton(Dialog)
        self.btnOrderLipton.setGeometry(QtCore.QRect(320, 330, 50, 30))
        self.btnOrderLipton.setAutoDefault(False)
        self.btnOrderLipton.setObjectName("btnOrderLipton")
        self.btnOrderLetsbeLatte = QtWidgets.QPushButton(Dialog)
        self.btnOrderLetsbeLatte.setGeometry(QtCore.QRect(270, 510, 50, 30))
        self.btnOrderLetsbeLatte.setAutoDefault(False)
        self.btnOrderLetsbeLatte.setObjectName("btnOrderLetsbeLatte")
        self.priceGhana2 = QtWidgets.QLabel(Dialog)
        self.priceGhana2.setGeometry(QtCore.QRect(70, 490, 50, 16))
        self.priceGhana2.setAlignment(QtCore.Qt.AlignCenter)
        self.priceGhana2.setObjectName("priceGhana2")
        self.btnOrderGatorade2 = QtWidgets.QPushButton(Dialog)
        self.btnOrderGatorade2.setGeometry(QtCore.QRect(370, 510, 50, 30))
        self.btnOrderGatorade2.setAutoDefault(False)
        self.btnOrderGatorade2.setObjectName("btnOrderGatorade2")
        self.priceGhana1 = QtWidgets.QLabel(Dialog)
        self.priceGhana1.setGeometry(QtCore.QRect(20, 490, 50, 16))
        self.priceGhana1.setAlignment(QtCore.Qt.AlignCenter)
        self.priceGhana1.setObjectName("priceGhana1")
        self.btnOrderGhana2 = QtWidgets.QPushButton(Dialog)
        self.btnOrderGhana2.setGeometry(QtCore.QRect(70, 510, 50, 30))
        self.btnOrderGhana2.setAutoDefault(False)
        self.btnOrderGhana2.setObjectName("btnOrderGhana2")
        self.btnOrderCocoGrape = QtWidgets.QPushButton(Dialog)
        self.btnOrderCocoGrape.setGeometry(QtCore.QRect(420, 510, 50, 30))
        self.btnOrderCocoGrape.setAutoDefault(False)
        self.btnOrderCocoGrape.setObjectName("btnOrderCocoGrape")
        self.btnOrderGatorade1 = QtWidgets.QPushButton(Dialog)
        self.btnOrderGatorade1.setGeometry(QtCore.QRect(320, 510, 50, 30))
        self.btnOrderGatorade1.setAutoDefault(False)
        self.btnOrderGatorade1.setObjectName("btnOrderGatorade1")
        self.imgLetsbeLatte = QtWidgets.QLabel(Dialog)
        self.imgLetsbeLatte.setEnabled(True)
        self.imgLetsbeLatte.setGeometry(QtCore.QRect(243, 380, 100, 100))
        self.imgLetsbeLatte.setText("")
        self.imgLetsbeLatte.setPixmap(QtGui.QPixmap("img/letsbeLatte.png"))
        self.imgLetsbeLatte.setScaledContents(True)
        self.imgLetsbeLatte.setObjectName("imgLetsbeLatte")
        self.imgLetsbe2 = QtWidgets.QLabel(Dialog)
        self.imgLetsbe2.setEnabled(True)
        self.imgLetsbe2.setGeometry(QtCore.QRect(143, 380, 100, 100))
        self.imgLetsbe2.setText("")
        self.imgLetsbe2.setPixmap(QtGui.QPixmap("img/letsbe.png"))
        self.imgLetsbe2.setScaledContents(True)
        self.imgLetsbe2.setObjectName("imgLetsbe2")
        self.imgCantata = QtWidgets.QLabel(Dialog)
        self.imgCantata.setEnabled(True)
        self.imgCantata.setGeometry(QtCore.QRect(193, 380, 100, 100))
        self.imgCantata.setText("")
        self.imgCantata.setPixmap(QtGui.QPixmap("img/cantata.png"))
        self.imgCantata.setScaledContents(True)
        self.imgCantata.setObjectName("imgCantata")
        self.imgPepsi_2 = QtWidgets.QLabel(Dialog)
        self.imgPepsi_2.setEnabled(True)
        self.imgPepsi_2.setGeometry(QtCore.QRect(43, 380, 100, 100))
        self.imgPepsi_2.setText("")
        self.imgPepsi_2.setPixmap(QtGui.QPixmap("img/ghana.png"))
        self.imgPepsi_2.setScaledContents(True)
        self.imgPepsi_2.setObjectName("imgPepsi_2")
        self.imgLetsbe1 = QtWidgets.QLabel(Dialog)
        self.imgLetsbe1.setEnabled(True)
        self.imgLetsbe1.setGeometry(QtCore.QRect(93, 380, 100, 100))
        self.imgLetsbe1.setText("")
        self.imgLetsbe1.setPixmap(QtGui.QPixmap("img/letsbe.png"))
        self.imgLetsbe1.setScaledContents(True)
        self.imgLetsbe1.setObjectName("imgLetsbe1")
        self.priceLetsbe1 = QtWidgets.QLabel(Dialog)
        self.priceLetsbe1.setGeometry(QtCore.QRect(120, 490, 50, 16))
        self.priceLetsbe1.setAlignment(QtCore.Qt.AlignCenter)
        self.priceLetsbe1.setObjectName("priceLetsbe1")
        self.priceLetsbe2 = QtWidgets.QLabel(Dialog)
        self.priceLetsbe2.setGeometry(QtCore.QRect(170, 490, 50, 16))
        self.priceLetsbe2.setAlignment(QtCore.Qt.AlignCenter)
        self.priceLetsbe2.setObjectName("priceLetsbe2")
        self.imgGatorade1 = QtWidgets.QLabel(Dialog)
        self.imgGatorade1.setEnabled(True)
        self.imgGatorade1.setGeometry(QtCore.QRect(293, 380, 100, 100))
        self.imgGatorade1.setText("")
        self.imgGatorade1.setPixmap(QtGui.QPixmap("img/gatorade.png"))
        self.imgGatorade1.setScaledContents(True)
        self.imgGatorade1.setObjectName("imgGatorade1")
        self.btnOrderLetsbe2 = QtWidgets.QPushButton(Dialog)
        self.btnOrderLetsbe2.setGeometry(QtCore.QRect(170, 510, 50, 30))
        self.btnOrderLetsbe2.setAutoDefault(False)
        self.btnOrderLetsbe2.setObjectName("btnOrderLetsbe2")
        self.btnOrderGhana1 = QtWidgets.QPushButton(Dialog)
        self.btnOrderGhana1.setGeometry(QtCore.QRect(20, 510, 50, 30))
        self.btnOrderGhana1.setAutoDefault(False)
        self.btnOrderGhana1.setObjectName("btnOrderGhana1")
        self.imgGhana1 = QtWidgets.QLabel(Dialog)
        self.imgGhana1.setEnabled(True)
        self.imgGhana1.setGeometry(QtCore.QRect(-7, 380, 100, 100))
        self.imgGhana1.setText("")
        self.imgGhana1.setPixmap(QtGui.QPixmap("img/ghana.png"))
        self.imgGhana1.setScaledContents(True)
        self.imgGhana1.setObjectName("imgGhana1")
        self.priceGatorade1 = QtWidgets.QLabel(Dialog)
        self.priceGatorade1.setGeometry(QtCore.QRect(320, 490, 50, 16))
        self.priceGatorade1.setAlignment(QtCore.Qt.AlignCenter)
        self.priceGatorade1.setObjectName("priceGatorade1")
        self.btnOrderSikhye = QtWidgets.QPushButton(Dialog)
        self.btnOrderSikhye.setGeometry(QtCore.QRect(470, 510, 50, 30))
        self.btnOrderSikhye.setAutoDefault(False)
        self.btnOrderSikhye.setObjectName("btnOrderSikhye")
        self.priceCantata = QtWidgets.QLabel(Dialog)
        self.priceCantata.setGeometry(QtCore.QRect(220, 490, 50, 16))
        self.priceCantata.setAlignment(QtCore.Qt.AlignCenter)
        self.priceCantata.setObjectName("priceCantata")
        self.btnOrderLetsbe1 = QtWidgets.QPushButton(Dialog)
        self.btnOrderLetsbe1.setGeometry(QtCore.QRect(120, 510, 50, 30))
        self.btnOrderLetsbe1.setAutoDefault(False)
        self.btnOrderLetsbe1.setObjectName("btnOrderLetsbe1")
        self.priceLetsbeLatte = QtWidgets.QLabel(Dialog)
        self.priceLetsbeLatte.setGeometry(QtCore.QRect(270, 490, 50, 16))
        self.priceLetsbeLatte.setAlignment(QtCore.Qt.AlignCenter)
        self.priceLetsbeLatte.setObjectName("priceLetsbeLatte")
        self.priceGatorade2 = QtWidgets.QLabel(Dialog)
        self.priceGatorade2.setGeometry(QtCore.QRect(370, 490, 50, 16))
        self.priceGatorade2.setAlignment(QtCore.Qt.AlignCenter)
        self.priceGatorade2.setObjectName("priceGatorade2")
        self.imgSparklingGrape_2 = QtWidgets.QLabel(Dialog)
        self.imgSparklingGrape_2.setEnabled(True)
        self.imgSparklingGrape_2.setGeometry(QtCore.QRect(443, 380, 100, 100))
        self.imgSparklingGrape_2.setText("")
        self.imgSparklingGrape_2.setPixmap(QtGui.QPixmap("img/sikhye.png"))
        self.imgSparklingGrape_2.setScaledContents(True)
        self.imgSparklingGrape_2.setObjectName("imgSparklingGrape_2")
        self.imgSparklingApple2_2 = QtWidgets.QLabel(Dialog)
        self.imgSparklingApple2_2.setEnabled(True)
        self.imgSparklingApple2_2.setGeometry(QtCore.QRect(393, 380, 100, 100))
        self.imgSparklingApple2_2.setText("")
        self.imgSparklingApple2_2.setPixmap(QtGui.QPixmap("img/cocoGrape.png"))
        self.imgSparklingApple2_2.setScaledContents(True)
        self.imgSparklingApple2_2.setObjectName("imgSparklingApple2_2")
        self.imgSparklingApple1_2 = QtWidgets.QLabel(Dialog)
        self.imgSparklingApple1_2.setEnabled(True)
        self.imgSparklingApple1_2.setGeometry(QtCore.QRect(343, 380, 100, 100))
        self.imgSparklingApple1_2.setText("")
        self.imgSparklingApple1_2.setPixmap(QtGui.QPixmap("img/gatorade.png"))
        self.imgSparklingApple1_2.setScaledContents(True)
        self.imgSparklingApple1_2.setObjectName("imgSparklingApple1_2")
        self.priceCocoGrape = QtWidgets.QLabel(Dialog)
        self.priceCocoGrape.setGeometry(QtCore.QRect(420, 490, 50, 16))
        self.priceCocoGrape.setAlignment(QtCore.Qt.AlignCenter)
        self.priceCocoGrape.setObjectName("priceCocoGrape")
        self.btnOrderCantata = QtWidgets.QPushButton(Dialog)
        self.btnOrderCantata.setGeometry(QtCore.QRect(220, 510, 50, 30))
        self.btnOrderCantata.setAutoDefault(False)
        self.btnOrderCantata.setObjectName("btnOrderCantata")
        self.priceSikhye = QtWidgets.QLabel(Dialog)
        self.priceSikhye.setGeometry(QtCore.QRect(470, 490, 50, 16))
        self.priceSikhye.setAlignment(QtCore.Qt.AlignCenter)
        self.priceSikhye.setObjectName("priceSikhye")
        self.btnReturn = QtWidgets.QPushButton(Dialog)
        self.btnReturn.setGeometry(QtCore.QRect(440, 550, 80, 30))
        self.btnReturn.setObjectName("btnReturn")
        self.btnReturn.setAutoDefault(False)
        self.btnInsert = QtWidgets.QPushButton(Dialog)
        self.btnInsert.setGeometry(QtCore.QRect(370, 550, 80, 30))
        self.btnInsert.setObjectName("btnInsert")
        self.btnInsert.setAutoDefault(False)
        self.lblPrice = QtWidgets.QLabel(Dialog)
        self.lblPrice.setGeometry(QtCore.QRect(295, 550, 75, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 53, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 168, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 3, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 53, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 3, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 53, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.lblPrice.setPalette(palette)
        self.lblPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPrice.setObjectName("lblPrice")
        self.imgCantata.raise_()
        self.imgPepsi_2.raise_()
        self.imgLetsbe1.raise_()
        self.imgSparklingGrape.raise_()
        self.imgCocorich2.raise_()
        self.imgTrevi2.raise_()
        self.imgCorn2.raise_()
        self.imgCorn1.raise_()
        self.imgLemon2.raise_()
        self.btnDeveloper.raise_()
        self.imgIcis1.raise_()
        self.imgLemon1.raise_()
        self.imgIcis2.raise_()
        self.imgIcis3.raise_()
        self.imgBurdock.raise_()
        self.imgTrevi1.raise_()
        self.btnOrderIcis2.raise_()
        self.priceIcis1.raise_()
        self.priceIcis2.raise_()
        self.priceLemon1.raise_()
        self.btnOrderIcis3.raise_()
        self.priceIcis3.raise_()
        self.btnOrderLemon1.raise_()
        self.priceCorn1.raise_()
        self.priceCorn2.raise_()
        self.priceBurdock.raise_()
        self.btnOrderLemon2.raise_()
        self.priceLemon2.raise_()
        self.btnOrderCorn2.raise_()
        self.btnOrderBurdock.raise_()
        self.btnOrderCorn.raise_()
        self.priceTrevi2.raise_()
        self.priceTrevi1.raise_()
        self.btnOrderTrevi2.raise_()
        self.btnOrderTrevi1.raise_()
        self.btnOrderIcis1.raise_()
        self.btnOrderSparklingGrape.raise_()
        self.imgCocorich1.raise_()
        self.imgSparklingApple2.raise_()
        self.btnOrderCocoRich1.raise_()
        self.imgCider.raise_()
        self.btnOrderSparklingApple1.raise_()
        self.imgMilkis.raise_()
        self.priceSparklingApple2.raise_()
        self.priceMilkis.raise_()
        self.imgHotsix.raise_()
        self.priceCocoRich1.raise_()
        self.btnOrderHotsix.raise_()
        self.btnOrderMilkis.raise_()
        self.btnOrderPepsi.raise_()
        self.priceCider.raise_()
        self.btnOrderCocoRich2.raise_()
        self.imgSparklingApple1.raise_()
        self.imgPepsi.raise_()
        self.imgLipton.raise_()
        self.priceLipton.raise_()
        self.btnOrderSparklingApple2.raise_()
        self.btnOrderCider.raise_()
        self.priceHotsix.raise_()
        self.pricePepsi.raise_()
        self.priceCocoRich2.raise_()
        self.priceOrderSparklingApple.raise_()
        self.priceSparklingApple1.raise_()
        self.btnOrderLipton.raise_()
        self.btnOrderLetsbeLatte.raise_()
        self.priceGhana2.raise_()
        self.btnOrderGatorade2.raise_()
        self.priceGhana1.raise_()
        self.btnOrderGhana2.raise_()
        self.btnOrderCocoGrape.raise_()
        self.btnOrderGatorade1.raise_()
        self.imgLetsbeLatte.raise_()
        self.imgLetsbe2.raise_()
        self.priceLetsbe1.raise_()
        self.priceLetsbe2.raise_()
        self.imgGatorade1.raise_()
        self.btnOrderLetsbe2.raise_()
        self.btnOrderGhana1.raise_()
        self.imgGhana1.raise_()
        self.priceGatorade1.raise_()
        self.btnOrderSikhye.raise_()
        self.priceCantata.raise_()
        self.btnOrderLetsbe1.raise_()
        self.priceLetsbeLatte.raise_()
        self.priceGatorade2.raise_()
        self.imgSparklingGrape_2.raise_()
        self.imgSparklingApple2_2.raise_()
        self.imgSparklingApple1_2.raise_()
        self.priceCocoGrape.raise_()
        self.btnOrderCantata.raise_()
        self.priceSikhye.raise_()
        self.btnReturn.raise_()
        self.btnInsert.raise_()
        self.lblPrice.raise_()

        self.retranslateUi(Dialog) # lambda: self.OrderDrink()
        self.btnOrderIcis1.clicked.connect(lambda: self.OrderDrink(0))
        self.btnDeveloper.clicked.connect(self.Developer)
        self.btnOrderIcis2.clicked.connect(lambda: self.OrderDrink(0))
        self.btnOrderIcis3.clicked.connect(lambda: self.OrderDrink(0))
        self.btnOrderLemon1.clicked.connect(lambda: self.OrderDrink(1))
        self.btnOrderLemon2.clicked.connect(lambda: self.OrderDrink(1))
        self.btnOrderCorn.clicked.connect(lambda: self.OrderDrink(2))
        self.btnOrderCorn2.clicked.connect(lambda: self.OrderDrink(2))
        self.btnOrderBurdock.clicked.connect(lambda: self.OrderDrink(3))
        self.btnOrderTrevi1.clicked.connect(lambda: self.OrderDrink(4))
        self.btnOrderTrevi2.clicked.connect(lambda: self.OrderDrink(4))
        self.btnOrderMilkis.clicked.connect(lambda: self.OrderDrink(5))
        self.btnOrderPepsi.clicked.connect(lambda: self.OrderDrink(6))
        self.btnOrderHotsix.clicked.connect(lambda: self.OrderDrink(7))
        self.btnOrderCider.clicked.connect(lambda: self.OrderDrink(8))
        self.btnOrderCocoRich1.clicked.connect(lambda: self.OrderDrink(9))
        self.btnOrderCocoRich2.clicked.connect(lambda: self.OrderDrink(9))
        self.btnOrderLipton.clicked.connect(lambda: self.OrderDrink(10))
        self.btnOrderSparklingApple1.clicked.connect(lambda: self.OrderDrink(11))
        self.btnOrderSparklingApple2.clicked.connect(lambda: self.OrderDrink(11))
        self.btnOrderSparklingGrape.clicked.connect(lambda: self.OrderDrink(12))
        self.btnOrderGhana1.clicked.connect(lambda: self.OrderDrink(13))
        self.btnOrderGhana2.clicked.connect(lambda: self.OrderDrink(13))
        self.btnOrderLetsbe1.clicked.connect(lambda: self.OrderDrink(14))
        self.btnOrderLetsbe2.clicked.connect(lambda: self.OrderDrink(14))
        self.btnOrderCantata.clicked.connect(lambda: self.OrderDrink(15))
        self.btnOrderLetsbeLatte.clicked.connect(lambda: self.OrderDrink(16))
        self.btnOrderGatorade1.clicked.connect(lambda: self.OrderDrink(17))
        self.btnOrderGatorade2.clicked.connect(lambda: self.OrderDrink(17))
        self.btnOrderCocoGrape.clicked.connect(lambda: self.OrderDrink(18))
        self.btnOrderSikhye.clicked.connect(lambda: self.OrderDrink(19))
        self.btnInsert.clicked.connect(self.InsertCoin)
        self.btnReturn.clicked.connect(self.ReturnCoin)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "E동 5층 자판기"))
        self.btnDeveloper.setText(_translate("Dialog", "한국산업기술대학교 2019156023 유광무"))
        self.btnOrderIcis2.setText(_translate("Dialog", "주문"))
        self.priceIcis1.setText(_translate("Dialog", "600원"))
        self.priceIcis2.setText(_translate("Dialog", "600원"))
        self.priceLemon1.setText(_translate("Dialog", "1500원"))
        self.btnOrderIcis3.setText(_translate("Dialog", "주문"))
        self.priceIcis3.setText(_translate("Dialog", "600원"))
        self.btnOrderLemon1.setText(_translate("Dialog", "주문"))
        self.priceCorn1.setText(_translate("Dialog", "1300원"))
        self.priceCorn2.setText(_translate("Dialog", "1300원"))
        self.priceBurdock.setText(_translate("Dialog", "1500원"))
        self.btnOrderLemon2.setText(_translate("Dialog", "주문"))
        self.priceLemon2.setText(_translate("Dialog", "1500원"))
        self.btnOrderCorn2.setText(_translate("Dialog", "주문"))
        self.btnOrderBurdock.setText(_translate("Dialog", "주문"))
        self.btnOrderCorn.setText(_translate("Dialog", "주문"))
        self.priceTrevi2.setText(_translate("Dialog", "1000원"))
        self.priceTrevi1.setText(_translate("Dialog", "1000원"))
        self.btnOrderTrevi2.setText(_translate("Dialog", "주문"))
        self.btnOrderTrevi1.setText(_translate("Dialog", "주문"))
        self.btnOrderIcis1.setText(_translate("Dialog", "주문"))
        self.btnOrderSparklingGrape.setText(_translate("Dialog", "주문"))
        self.btnOrderCocoRich1.setText(_translate("Dialog", "주문"))
        self.btnOrderSparklingApple1.setText(_translate("Dialog", "주문"))
        self.priceSparklingApple2.setText(_translate("Dialog", "1000원"))
        self.priceMilkis.setText(_translate("Dialog", "800원"))
        self.priceCocoRich1.setText(_translate("Dialog", "1000원"))
        self.btnOrderHotsix.setText(_translate("Dialog", "주문"))
        self.btnOrderMilkis.setText(_translate("Dialog", "주문"))
        self.btnOrderPepsi.setText(_translate("Dialog", "주문"))
        self.priceCider.setText(_translate("Dialog", "1000원"))
        self.btnOrderCocoRich2.setText(_translate("Dialog", "주문"))
        self.priceLipton.setText(_translate("Dialog", "1000원"))
        self.btnOrderSparklingApple2.setText(_translate("Dialog", "주문"))
        self.btnOrderCider.setText(_translate("Dialog", "주문"))
        self.priceHotsix.setText(_translate("Dialog", "1000원"))
        self.pricePepsi.setText(_translate("Dialog", "800원"))
        self.priceCocoRich2.setText(_translate("Dialog", "1000원"))
        self.priceOrderSparklingApple.setText(_translate("Dialog", "1000원"))
        self.priceSparklingApple1.setText(_translate("Dialog", "1000원"))
        self.btnOrderLipton.setText(_translate("Dialog", "주문"))
        self.btnOrderLetsbeLatte.setText(_translate("Dialog", "주문"))
        self.priceGhana2.setText(_translate("Dialog", "600원"))
        self.btnOrderGatorade2.setText(_translate("Dialog", "주문"))
        self.priceGhana1.setText(_translate("Dialog", "600원"))
        self.btnOrderGhana2.setText(_translate("Dialog", "주문"))
        self.btnOrderCocoGrape.setText(_translate("Dialog", "주문"))
        self.btnOrderGatorade1.setText(_translate("Dialog", "주문"))
        self.priceLetsbe1.setText(_translate("Dialog", "600원"))
        self.priceLetsbe2.setText(_translate("Dialog", "600원"))
        self.btnOrderLetsbe2.setText(_translate("Dialog", "주문"))
        self.btnOrderGhana1.setText(_translate("Dialog", "주문"))
        self.priceGatorade1.setText(_translate("Dialog", "800원"))
        self.btnOrderSikhye.setText(_translate("Dialog", "주문"))
        self.priceCantata.setText(_translate("Dialog", "1000원"))
        self.btnOrderLetsbe1.setText(_translate("Dialog", "주문"))
        self.priceLetsbeLatte.setText(_translate("Dialog", "1000원"))
        self.priceGatorade2.setText(_translate("Dialog", "800원"))
        self.priceCocoGrape.setText(_translate("Dialog", "800원"))
        self.btnOrderCantata.setText(_translate("Dialog", "주문"))
        self.priceSikhye.setText(_translate("Dialog", "800원"))
        self.btnReturn.setText(_translate("Dialog", "현금 반환"))
        self.btnInsert.setText(_translate("Dialog", "현금 투입"))
        self.lblPrice.setText(_translate("Dialog", "0원"))

    def OrderDrink(self, index):
        global drinkName, drinkPrice, drinkCount

        price = drinkPrice[index]

        if drinkCount[index] > 0:
            # for i in range(len(list(machineCoin.coin.keys()))):
                # if insertCoin.GetCoinIndex(i) <= machineCoin.GetCoinIndex(i):
                    # print("ERROR:", machineCoin.GetCoinIndex(i)[0])
                    # 동전 없다는 경고 띄어주기
                    # return False

            if insertCoin.GetSum() >= price:
                for coin in list(insertCoin.coin.keys()):
                    if insertCoin.GetCoin(coin) <= 0:
                        break

                    count = price // coin
                    price -= coin * count

                    insertCoin.DecreaseCoin(coin, count)
                    print("PRICE:", price)
                    print("SET COIN:", coin)
                    print("GET COIN:", insertCoin.GetCoin(coin))
                    print("GET COUNT:", insertCoin.GetCoin(coin) // coin)
                    print("-----------")
                    # print(insertCoin.GetSum())

                QMessageBox.about(Dialog, "음료수 구매 성공", drinkName[index] + "(을)를 " + str(drinkPrice[index]) + "원에 구매하였습니다.\n남은 갯수: " + str(drinkCount[index]) + "개")
                ui.lblPrice.setText(str(insertCoin.GetSum()) + "원")
                Dialog.repaint()
            else:
                QMessageBox.about(Dialog, "음료수 구매 실패", "금액이 부족합니다")


        # if coin >= drinkPrice[index]:
        #     if drinkCount[index] > 0:
        #         coin -= drinkPrice[index]
        #         drinkCount[index] -= 1
        #
        #         QMessageBox.about(Dialog, "음료수 구매 성공", drinkName[index] + "(을)를 " + str(drinkPrice[index]) + "원에 구매하였습니다.\n남은 갯수: " + str(drinkCount[index]) + "개")
        #         ui.lblPrice.setText(str(coin) + "원")
        #         Dialog.repaint()
        #
        #         URL = 'https://haeyum.ml/PHPMailer/vendingMachine/api/bought?drinkName=' + drinkName[index] + '&drinkCount=' + str(drinkCount[index])
        #
        #         response = requests.get(URL)
        #     else:
        #         QMessageBox.about(Dialog, "음료수 구매 실패", drinkName[index] + " 음료수의 갯수가 없습니다")
        # else:
        #     QMessageBox.about(Dialog, "음료수 구매 실패", "금액이 부족합니다")

    def Developer(self, test):
        QMessageBox.about(Dialog, "개발자 정보", "한국산업기술대학교 2019156023 유광무\n1학년 1학기 전산학기초 자판기 과제")

    def InsertCoin(self):
        # i, okPressed = QInputDialog.getInt(Dialog, "현금 투입", "투입할 금액을 입력해주세요\n(최대 투입 금액: 10,000원)", 100, 0, 19000, 1)
        i, okPressed = QInputDialog.getInt(Dialog, "현금 투입", "투입할 1000원 지폐의 갯수를 입력해주세요")
        insertCoin.IncreaseCoin(1000, i)
        machineCoin.IncreaseCoin(1000, i)

        i, okPressed = QInputDialog.getInt(Dialog, "현금 투입", "투입할 500원 동전의 갯수를 입력해주세요")
        insertCoin.IncreaseCoin(500, i)
        machineCoin.IncreaseCoin(500, i)

        i, okPressed = QInputDialog.getInt(Dialog, "현금 투입", "투입할 100원 동전의 갯수를 입력해주세요")
        insertCoin.IncreaseCoin(100, i)
        machineCoin.IncreaseCoin(100, i)

        i, okPressed = QInputDialog.getInt(Dialog, "현금 투입", "투입할 50원 동전의 갯수를 입력해주세요")
        insertCoin.IncreaseCoin(50, i)
        machineCoin.IncreaseCoin(50, i)

        i, okPressed = QInputDialog.getInt(Dialog, "현금 투입", "투입할 10원 동전의 갯수를 입력해주세요")
        insertCoin.IncreaseCoin(10, i)
        machineCoin.IncreaseCoin(10, i)

        ui.lblPrice.setText(str(insertCoin.GetSum()) + "원")
        Dialog.repaint()

    def ReturnCoin(self):
        QMessageBox.about(Dialog, "현금 반환", "현금을 " + str(insertCoin.GetSum()) + "원을 반환하였습니다")
        insertCoin.Reset()

        ui.lblPrice.setText(str(insertCoin.GetSum()) + "원")
        Dialog.repaint()

    def CheckDrinkCount(self, index):
        if drinkCount[index] > 0:
            drinkCount[index] -= 1

    def CheckCoin(self):
        # if list(insertCoin.values()) <= list(machineCoin.values())[i]:

        for i in range(len(list(machineCoin.coin.keys()))):
            if insertCoin.GetCoinIndex(i) <= machineCoin.GetCoinIndex(i):
                print("ERROR:", machineCoin.GetCoinIndex(i)[0])
                return False

        return True

    def CheckPrice(self, price):
        if insertCoin.GetCoin() >= price:
            return True
        else:
            return False


machineCoin = Coin()
insertCoin = Coin()

drinkName = []
drinkPrice = []
drinkCount = []


def AddDrink(name, price, count):
    global drinkName, drinkPrice, drinkCount

    drinkName.append(name)
    drinkPrice.append(price)
    drinkCount.append(count)


def Init():
    AddDrink("아이시스", 600, 5)
    AddDrink("레몬워터", 1500, 5)
    AddDrink("옥수수 수염차", 1300, 5)
    AddDrink("초가을 우엉차", 1300, 5)
    AddDrink("트레비", 1000, 5)
    AddDrink("밀키스", 800, 5)
    AddDrink("펩시", 800, 5)
    AddDrink("핫식스", 1000, 5)
    AddDrink("사이다", 1000, 5)
    AddDrink("코코 리치", 1000, 5)
    AddDrink("립톤", 1000, 5)
    AddDrink("스파클링 사과", 1000, 5)
    AddDrink("스파클링 포도", 1000, 5)
    AddDrink("가나", 600, 5)
    AddDrink("레쓰비", 600, 5)
    AddDrink("칸타타", 1000, 5)
    AddDrink("레쓰비 카페타임", 1000, 5)
    AddDrink("게토레이", 800, 5)
    AddDrink("코코 포도", 800, 5)
    AddDrink("잔치집 식혜", 800, 5)


def Main():
    Init()


if __name__ == "__main__":
    Init()

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UiDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

# global drinkName
# print(drinkName)
